#!/bin/bash

# Color definitions for terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}===============================================================${NC}"
echo -e "${PURPLE}         VOIDORA CLOUD DASHBOARD - VPS & CLOUDFLARE SETUP       ${NC}"
echo -e "${CYAN}===============================================================${NC}"

# Check if OS is Debian or Ubuntu
if [ ! -f /etc/debian_version ]; then
    echo -e "${RED}[x] This VPS script is optimized for Debian/Ubuntu systems.${NC}"
    echo -e "You can still run it, but package installation may fail depending on your package manager."
    read -p "Do you want to continue? (y/n) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# 1. Update VPS Packages
echo -e "\n${BLUE}[1/5] Updating system packages...${NC}"
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install -y curl build-essential git software-properties-common lsb-release

# 2. Install Node.js (NodeSource LTS)
echo -e "\n${BLUE}[2/5] Installing Node.js & npm...${NC}"
if ! command -v node &> /dev/null; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt-get install -y nodejs
else
    echo -e "${GREEN}[✓] Node.js is already installed: $(node -v)${NC}"
fi

# Install PM2 globally to run the process persistently
echo -e "\n${BLUE}[3/5] Installing PM2 process manager globally...${NC}"
sudo npm install -g pm2

# 3. Download / Install Cloudflare Tunnel Client (cloudflared)
echo -e "\n${BLUE}[4/5] Installing Cloudflare Tunnel (cloudflared)...${NC}"
if ! command -v cloudflared &> /dev/null; then
    echo -e "Adding Cloudflare package repository..."
    sudo mkdir -p --mode=0755 /usr/share/keyrings
    curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
    echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflare-main.deb $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/cloudflare-main.list
    sudo apt-get update && sudo apt-get install -y cloudflared
else
    echo -e "${GREEN}[✓] cloudflared is already installed: $(cloudflared --version)${NC}"
fi

# 4. Project Setup & Dependency Installation
echo -e "\n${BLUE}[5/5] Preparing Project Dependencies...${NC}"
npm install --production

# Create default .env if not present
if [ ! -f "dash/.env" ]; then
    echo -e "${YELLOW}[!] Creating default dash/.env configuration file...${NC}"
    mkdir -p dash
    cat <<EOT > dash/.env
RAZORPAY_KEY_ID=rzp_test_1234567890abcdef
RAZORPAY_KEY_SECRET=AbCdEfGhIjKlMnOpQrSt
PORT=3000
EOT
    echo -e "${GREEN}[✓] Default dash/.env configured.${NC}"
fi

# Start app with PM2
echo -e "\n${BLUE}[✓] Starting Voidora Cloud Dashboard in the background using PM2...${NC}"
pm2 stop "voidora-cloud-dash" &> /dev/null || true
pm2 delete "voidora-cloud-dash" &> /dev/null || true
pm2 start dash/app.js --name "voidora-cloud-dash" --env PORT=3000

# Configure PM2 startup hook to keep the server running across reboots
sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u $USER --hp $HOME
pm2 save

echo -e "\n${GREEN}===============================================================${NC}"
echo -e "🌟  ${GREEN}BASIC VPS INSTALLATION COMPLETED SUCCESSFULLY!${NC}  🌟"
echo -e "===============================================================${NC}"
echo -e "Your application is now running in the background via PM2 on ${CYAN}port 3000${NC}."
echo -e ""
echo -e "${YELLOW}===============================================================${NC}"
echo -e "         STEPS TO CONNECT WITH YOUR CLOUDFLARE DOMAIN          "
echo -e "${YELLOW}===============================================================${NC}"
echo -e "To route external secure traffic from your Cloudflare domain to this VPS app on port 3000, please perform the following:"
echo -e ""
echo -e "Option A: Quick Temporary Public URL (For testing)"
echo -e "  Simply run: ${CYAN}cloudflared tunnel --url http://localhost:3000${NC}"
echo -e ""
echo -e "Option B: Permanent Secure Tunnel with Your Domain (Recommended)"
echo -e "  1. Authenticate cloudflared with your Cloudflare account:"
echo -e "     ${CYAN}cloudflared tunnel login${NC}"
echo -e "     (Click the link displayed in the terminal to authorize your domain)"
echo -e ""
echo -e "  2. Create your tunnel:"
echo -e "     ${CYAN}cloudflared tunnel create voidora-dash-tunnel${NC}"
echo -e "     (Copy the Tunnel ID generated by this command)"
echo -e ""
echo -e "  3. Route the tunnel to your domain/subdomain:"
echo -e "     ${CYAN}cloudflared tunnel route dns voidora-dash-tunnel yourdomain.com${NC}"
echo -e ""
echo -e "  4. Create a cloudflared configuration file at ${CYAN}~/.cloudflared/config.yml${NC}:"
echo -e "     ----------------------------------------"
echo -e "     tunnel: <your-tunnel-id>"
echo -e "     credentials-file: /home/$USER/.cloudflared/<your-tunnel-id>.json"
echo -e "     "
echo -e "     ingress:"
echo -e "       - hostname: yourdomain.com"
echo -e "         service: http://localhost:3000"
echo -e "       - service: http_status:404"
echo -e "     ----------------------------------------"
echo -e ""
echo -e "  5. Install and start cloudflared as a system daemon:"
echo -e "     ${CYAN}sudo cloudflared --config ~/.cloudflared/config.yml service install${NC}"
echo -e "     ${CYAN}sudo systemctl start cloudflared${NC}"
echo -e "     ${CYAN}sudo systemctl enable cloudflared${NC}"
echo -e ""
echo -e "${GREEN}===============================================================${NC}"
echo -e "Your VPS is now configured and ready to be routed securely via Cloudflare!"
echo -e "===============================================================${NC}"
